font=JetBrainsMonoNL NF:size=20

[text-bindings]

# tmux new window
\x02c = Mod4+n
\x02c = Mod4+t

# tmux window chooser
\x02W = Mod4+w

# clear
clear\x0d = Mod4+k

# tmux next / previous window
\x02n = Mod4+Tab
\x02p = Mod4+Shift+Tab

[colors-dark]
alpha=0.9
foreground=ffffff
background=000000
