#pragma once

#define NO_DEBUG
#define NO_PRINT
#define NO_USB_STARTUP_CHECK

#define MOUSEKEY_INERTIA

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 8

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 64

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 40

#undef MOUSEKEY_FRICTION
#define MOUSEKEY_FRICTION 1

#undef MOUSEKEY_MOVE_DELTA
#define MOUSEKEY_MOVE_DELTA 1
