$mod = SUPER

monitor = Virtual-1, 3840x2160@120, auto, 2

exec-once = hyprpaper

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0

    layout = dwindle
}

decoration {
    rounding = 0 

    blur {
        enabled = false
    }
}

animations {
    enabled = no 
}

# Terminal
$terminal = foot

# Application launcher
$menu = wofi --show drun

# Keybindings
bind = $mod, Backspace, exec, $terminal
bind = $mod, SPACE, exec, $menu

bind = $mod, Q, killactive
bind = $mod, M, exit
bind = SUPER, W, sendshortcut, CTRL, W, active
bind = SUPER, T, sendshortcut, CTRL, T, active
bind = SUPER, R, sendshortcut, CTRL, R, active

# Workspaces
bind = $mod, F1, workspace, 1
bind = $mod, F2, workspace, 2
bind = $mod, F3, workspace, 3
bind = $mod, F4, workspace, 4
bind = $mod, F5, workspace, 5
